### ISSUE TITLE
A3.0 Failed to start the game

### ISSUE THREAD

**Issue by Thirace446** [benbenlaw/caveopolis#11]
I also notice that this problem on the server, Disable mod Update Detection can enable the server.
But it doesn't seem to work on the client side.
https://0x0.st/o2cM.txt

**Comment by LotP1** [comment]
see issue #10

**Comment by LotP1** [comment]
also how did you download the client onto MMC? from what i know mmc no longer supports downloading curseforge only mods

**Comment by Thirace446** [comment]
> 
I actually use PolyMC (
Of course you can use MultiMC if you want to.
Just download the consolidation package and move the file to MMC.

**Comment by Thirace446** [comment]
> also how did you download the client onto MMC? from what i know mmc no longer supports downloading curseforge only mods

I actually use PolyMC (
Of course you can use MultiMC if you want to.
Just download the consolidation package and move the file to MMC.

**Comment by Thirace446** [comment]
> see issue #10

I did this on the server but it doesn't work on the client.

**Comment by Thirace446** [comment]
> see issue #10

It looks like they're the same problem.
But it still cannot launch the game on the client side.

**Comment by Thirace446** [comment]
Actually the problem happened on my friend's computer, not me.

**Comment by LotP1** [comment]
If it's a client issue i suggest trying to reinstall the client.
remember to make sure all the curseforge only mods are still installed.
