### ISSUE TITLE
A4.0 Dragon Egg still not working with Enderium Ingot while in the End

### ISSUE THREAD

**Issue by TacoMage** [benbenlaw/caveopolis#12]
The dragon egg issue still seems to exist for A4 even after the fix, but only in the End.  Shift-Right-Clicking with the ingot shows a cooldown scroll vertically behind the ingot, but no other effect happens while in the End dimension.  If done in the overworld (cave) dimension, the egg drops as intended.

This was tested in freshly generated single player and server worlds with the same behavior observed.

**Comment by benbenlaw** [comment]
actually fixed in A5.0
