### ISSUE TITLE
No Lasers LaserIO

### ISSUE THREAD

**Issue by KBizzle** [benbenlaw/caveopolis#15]
LaserIO connectors are not showing the laser. Making it difficult to see what is connected. Particles transferring items and liquids do show, just not the laser connections. It seems if you are careful, items still transfer properly, just no visual display of the connection. I attempted to manually update LaserIO and it still did not correct the issue.

**Comment by Epicycle23** [comment]
It's a bug with tempad.
You can set   ´timedoorFancy": false´ in config/tempad_client.json to fix it.

**Comment by moody69420** [comment]
very odd that with same settings dw20 1.18 doesnt do this

**Comment by Epicycle23** [comment]
Dire wrote about this issue and how to fix it, I think he wrote something about it being fixed in a later version of tempad.

**Comment by Epicycle23** [comment]
https://github.com/Direwolf20-MC/LaserIO/issues/58#issuecomment-1164716797
And yes it works, I had to turn it off again after the update, didn't notice any "unfancy" portals either ;)
