### ISSUE TITLE
Suggestion: Switch Red Sand Layers

### ISSUE THREAD

**Issue by MaxAstro** [benbenlaw/caveopolis#21]
Mining bitumen is extremely annoying because of being a gravity block with another layer of gravity block on top of it.

Would it be possible to switch the bitumen and red sandstone layers, so that the bitumen is sandwiched by non-gravity layers? Obviously it's too late to help my world, but it might help the next person. :)

**Comment by JoelGodOfwar** [comment]
Using a torch under the sandstone then breaking the sandstone gets you the whole stack. You can get a stack of both sands within 5 minutes easy.
