### ISSUE TITLE
Dragon Infuser and Everything combiner deletes items if there is not enough power

### ISSUE THREAD

**Issue by jthe111** [benbenlaw/caveopolis#34]
As the title suggests, the dragon infuser and everything combiner if they do not have enough power will delete items as if they are constantly trying to reset the machine. Don't know if this is intended but it burned nearly two stacks of wither skelly skulls and an entire batch of cave stone in the combiner.

**Comment by humanitea** [comment]
Fixed, now DI and EC will require an amount of energy as opposed to a constant amount per tick.
