### ISSUE TITLE
End Portal not activated when placing eyes of ender

### ISSUE THREAD

**Issue by arisgoun** [benbenlaw/caveopolis#35]
After placing the eyes of ender at the portal blocks, the portal is not activated.

Then removing the portal blocks (rigjt-click with an enderium ingot) the portal blocks are recovered but the eyes of ender are lost.

Version 4.1

**Comment by Blackolf** [comment]
I had the same probleme before , make sure you place the portal frame at the right direction ![image](https://user-images.githubusercontent.com/50931435/199960508-79733666-3a2e-43f9-8517-675b497754d5.jpeg)

**Comment by arisgoun** [comment]
Indeed, that was the problem.
