### ISSUE TITLE
Patchouli Guide Book Broken

### ISSUE THREAD

**Issue by Nicole-Evermore** [benbenlaw/caveopolis#36]
As of version 4.1, the patchouli guide book for the pack is listed as Invalid. Checking the file structure, the data for the book is still there, but I guess something has split the connection...
![javaw_xc8Y6fGOFb](https://user-images.githubusercontent.com/40040673/200467372-99534aff-a12a-4deb-9522-0e37ed8061e7.png)

**Comment by Nicole-Evermore** [comment]
Update: The custom main menu also doesn't show up anymore.

**Comment by humanitea** [comment]
Can you provide any more details on this issue? Guide book and Fancy Menu are both working correctly on 4.1. Did you download the pack through curseforge or elsewhere?

**Comment by Nicole-Evermore** [comment]
Downloaded and updated using Curseforge.

**Comment by humanitea** [comment]
Found the issue when updating. Thanks for the report! Fixed in 4.3
