### ISSUE TITLE
how the heck did this guy spawn here 

### ISSUE THREAD

**Issue by Jiriki79** [benbenlaw/caveopolis#37]
![2022-11-29_23 28 02](https://user-images.githubusercontent.com/43390202/204715192-0720f94d-e2e4-4039-bb56-9289070c15ef.png)

**Comment by Jiriki79** [comment]
i have light level overlay always turned on btw

**Comment by humanitea** [comment]
Could not replicate, if this is reported again I will look into it further. Possibly something to do with InControl's spawning.
