### ISSUE TITLE
A.30 Server Files

### ISSUE THREAD

**Issue by Saphrym** [benbenlaw/caveopolis#9]
Server files for version A.30 have client side only mods that are causing servers to crash. Such as Rubidium. I don't know exactly which ones are safe to remove to make the server work with the client, so could you fix that when you get a chance?

**Comment by Novtalath** [comment]
I have disabled Rubidium (comes as two files) on the server side - server started no problem. Client connected with no issues.
![image](https://user-images.githubusercontent.com/13785880/183506025-bdee9c2f-e5be-4fdd-9d63-ca659fb94fab.png)

**Comment by 13ofDragons** [comment]
Ok. Thanks. I know a few server hosts that use automation for this, so hopefully you can publish a new version with the fixes in the future. :)
